server:
  port: 81

logging:
  level:
    spittr: DEBUG
spring:
  artemis:
    user: artemis
    password: simetraehcapa
  application.name: Bootstrap Spring Boot
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
spittr:
  reference-url: http://127.0.0.1:8081/data/references