server:
  port: 80

logging:
  level:
    spittr: DEBUG
spring:
  application.name: Bootstrap Spring Boot
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
spittr:
  db-proxy-url: http://127.0.0.1:8080/data